package com.example.neolabs.enums;

public enum EntityEnum {

    USER,
    APPLICATION,
    GROUP,
    MARKETING_STRATEGY,
    STUDENT,
    COURSE,
    DEPARTMENT,
    MENTOR,
    SCHEDULE,
    PAYMENT,
    MONTH_BILL,
    SCHEDULE_UNIT,
    STUDENT_GROUP_BILL,

    APPLICATION_OPERATION,
    USER_OPERATION,
    GROUP_OPERATION,
    COURSE_OPERATION,
    DEPARTMENT_OPERATION,
    MENTOR_OPERATION,
    STUDENT_OPERATION,
    PAYMENT_OPERATION
}
